//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksApi.Dal
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TasksDBEntities : DbContext
    {
        public TasksDBEntities()
            : base("name=TasksDBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Task>()
          .Property(a => a.Task_ID)
          .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            modelBuilder.Entity<Parent_Task>()
         .Property(a => a.Parent_ID)
         .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        }

        public virtual DbSet<Parent_Task> Parent_Task { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
